# Generated by Django 5.2.9 on 2025-12-05 19:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID кошелька')),
                ('wallet_name', models.CharField(max_length=60, verbose_name='Название кошелька')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Баланс')),
                ('version', models.IntegerField(default=0, verbose_name='Версия')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Технический кошелек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
                'db_table': 'wallets',
                'indexes': [models.Index(fields=['wallet_id'], name='wallets_wallet__11a55a_idx'), models.Index(fields=['is_admin'], name='wallets_is_admi_ea8649_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма перевода')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Комиссия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='core_transactions.wallet', verbose_name='Кошелек отправителя')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='core_transactions.wallet', verbose_name='Кошелек получателя')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'), models.Index(fields=['from_wallet', 'to_wallet'], name='transaction_from_wa_98481d_idx')],
            },
        ),
    ]
